# Generated by Django 4.2.13 on 2024-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(default=1, upload_to="menu"),
            preserve_default=False,
        ),
    ]
