# Generated by Django 4.2.13 on 2024-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_menuitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
