# Generated by Django 4.2.13 on 2024-06-27 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_table_available"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
