# Generated by Django 4.2.13 on 2024-06-27 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_booking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
